version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
       - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
       - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --only-group docs
    build:
      html:
        - ls -al
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - make -C docs html
        - cp -r docs/_build/html $READTHEDOCS_OUTPUT/html/
