name: Tests & checks

on:
  pull_request:
  workflow_dispatch: # allow running manually from the Actions tab

# cancel previous runs on a new commit
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # set version (e.g. 1.2.3) from the latest Git tag on master branch
      - name: Set package release version
        # :11 changes "refs/tags/v1.2.3" to "1.2.3", where "v1.2.3" is tag string
        # timestamp "YYYYMMDDHHMMSS" is added at the end
        run: |
          echo ${GITHUB_REF}
