name: Test documentation

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'skfp/**'
      - '.github/workflows/**'
  workflow_dispatch: # allow running manually from the Actions tab

# cancel previous runs on a new commit
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install the project dependencies
        run: poetry install --with doc

      - name: Build documentation
        run: poetry run make docs

